### PR TITLE
Stretch feature note taking-Kenneth W. 

### PR DESCRIPTION
**Pull request by Kenneth-Y-Wang**
https://user-images.githubusercontent.com/88110300/136442325-7b459b69-3a30-4fa2-bbe4-6c9ca75332bb.mov

now the dropdown menu is added when the screen is smaller than 1250px of width, all pages can be accessed from top nav bar, and the main two features: pic search and note log can also be accessed from dashboard

### CODE REVIEW

**Comment by Kenneth-Y-Wang** [comment]
https://user-images.githubusercontent.com/88110300/136442643-c025f177-11e7-4538-8572-3ff71a50e84c.mov

further explanation of all views accessing

**Comment by Kenneth-Y-Wang** [comment]
https://user-images.githubusercontent.com/88110300/136442791-414352e5-1c85-438f-9b6d-eaa8d20086f3.mov

partial reminder will show on both dashboard and reminder section with'...', and user can touch each reminder bar to see the detail reminder ( has feature explanation on webpage)

**Comment by Kenneth-Y-Wang** [comment]
https://user-images.githubusercontent.com/88110300/136443053-d12ae9cb-1df0-4181-bfcc-da987c8da3e9.mov

added feature explanation on the search feature, and once user save the pic, the page will go to gallery. user can re-enter search page by clicking new search no the top right corner.

**Comment by Kenneth-Y-Wang** [comment]
https://user-images.githubusercontent.com/88110300/136443351-10659f2c-648c-414a-9b73-09f0b06fcf2c.mov

user can sort note by category( with feature explanation on page), and change pic to profile and change profile pic background color

**Comment by Kenneth-Y-Wang** [comment]
https://user-images.githubusercontent.com/88110300/136443664-66a96d6a-cd74-4eda-a9d3-4cde5f94c9da.mov

user can edit/delete both reminder and personal puppy note. the reminder adjustment will also show on main page reminder preview

**Comment by Kenneth-Y-Wang** [comment]
https://user-images.githubusercontent.com/88110300/136444049-ff46aaf5-8857-4d57-8334-a86159488cd3.mov

now the game feature has better explanation, also the sort feature has explanation

**Review by thebearingedge — APPROVED** [review]

**Pull request merged**
